#!/bin/bash

#SBATCH --time=20:00
#SBATCH --mail-type=ALL
#SBATCH --account=PAS1067
#SBATCH --job-name=permutation_importance
#SBATCH --output=output_permutation_importance
#SBATCH --gpus-per-node=1

# This script is for running the feature selection tool on a cluster

# Loading of necessary modules for TensorFlow to work
module load python/3.6 cuda/8.0.44

# Code which calculates the feature importance
python3 permutation_importance.py
