#!/bin/bash

#SBATCH --time=20:00
#SBATCH --mail-type=ALL
#SBATCH --account=PAS1067
#SBATCH --job-name=overfitting
#SBATCH --output=output_overfitting
#SBATCH --gpus-per-node=1


# Copyright (C) <2025>  <The Ohio State University>       

# This program is free software: you can redistribute it and/or modify                              
# it under the terms of the GNU General Public License as published by 
# the Free Software Foundation, either version 3 of the License, or    
# (at your option) any later version.                                                                                       
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of           
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       
# GNU General Public License for more details.                                                                             

# You should have received a copy of the GNU General Public License 
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# This script is for running the feature selection tool on a cluster
# adjust time and resources request above. 

# Loading of necessary modules for TensorFlow to work
module load python/3.6 cuda/8.0.44

# Code which creates the model
python3 overfitting.py
