#!/bin/bash

#SBATCH --time=20:00
#SBATCH --mail-type=ALL
#SBATCH --account=PAS1067
#SBATCH --job-name=permutations_models
#SBATCH --output=output_permutation_models
#SBATCH --gpus-per-node=1

# This script is for running the feature selection tool on a cluster
# adjust time and resources request above. 

# Loading of necessary modules for TensorFlow to work
module load python/3.6 cuda/8.0.44

# Code which creates the models
python3 permutation_models.py
